services:

    etudiant.form.registration:
        class: Utilisateurs\UtilisateursBundle\Form\EtudiantRegistrationType
        tags:
            - {name: form.type, alias: etudiant_user_registration}
            