utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

permisfute:
    resource: "@PermisfuteBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

Utilisateurs :
    resource: "@UtilisateursBundle/Controller/"
    type: annotation
    prefix: /
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin